// <auto-generated />
namespace UrlShortener.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_url_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_url_description));
        
        string IMigrationMetadata.Id
        {
            get { return "202203211132262_added_url_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
